### ISSUE TITLE
php PDO extension or PDO-MySQL driver is not available

### ISSUE THREAD

**Issue by mr-manuel** [Froxlor/Froxlor#1057]
**Describe the bug**
Error message in `var/mail/root` after upgrading from `0.10.38.2` to `0.10.38.3`.

```
From root@srvweb01.domain.tld  Wed Dec 14 21:09:01 2022
Return-Path: <root@srvweb01.domain.tld>
X-Original-To: root
Delivered-To: root@srvweb01.domain.tld
Received: by srvweb01.domain.tld (Postfix, from userid 0)
        id 4972328560B; Wed, 14 Dec 2022 21:09:01 +0100 (CET)
From: root@srvweb01.domain.tld (Cron Daemon)
To: root@srvweb01.domain.tld
Subject: Cron <root@srvweb01> /usr/bin/nice -n 5 /usr/bin/php -q /var/www/froxlor/scripts/php-sessionclean.php --froxlor-dir='/var/www/froxlor/' 1> /dev/null
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
X-Cron-Env: <PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <LOGNAME=root>
Message-Id: <20221214200901.4972328560B@srvweb01.domain.tld>
Date: Wed, 14 Dec 2022 21:09:01 +0100 (CET)

froxlor[3245674]: The php PDO extension or PDO-MySQL driver is not available
froxlor[3245674]: --- DEBUG: #0 /var/www/froxlor/lib/Froxlor/Database/Database.php(219): Froxlor\Database\Database::getDB() #1 /var/www/froxlor/lib/Froxlor/Settings.php(84): Froxlor\Database\Database::__callStatic() #2 /var/www/froxlor/lib/Froxlor/Settings.php(67): Froxlor\Settings::readSettings() #3 /var/www/froxlor/lib/Froxlor/Settings.php(122): Froxlor\Settings::init() #4 /var/www/froxlor/lib/Froxlor/Cli/Action/PhpSessioncleanAction.php(20): Froxlor\Settings::Get() #5 /var/www/froxlor/lib/Froxlor/Cli/CmdLineHandler.php(64): Froxlor\Cli\Action\PhpSessioncleanAction->run() #6 /var/www/froxlor/lib/Froxlor/Cli/CmdLineHandler.php(47): Froxlor\Cli\CmdLineHandler->__construct() #7 /var/www/froxlor/scripts/php-sessionclean.php(28): Froxlor\Cli\CmdLineHandler::processParameters() #8 {main}



From root@srvweb01.domain.tld  Wed Dec 14 21:10:01 2022
Return-Path: <root@srvweb01.domain.tld>
X-Original-To: root
Delivered-To: root@srvweb01.domain.tld
Received: by srvweb01.domain.tld (Postfix, from userid 0)
        id 5901528560A; Wed, 14 Dec 2022 21:10:01 +0100 (CET)
From: root@srvweb01.domain.tld (Cron Daemon)
To: root@srvweb01.domain.tld
Subject: Cron <root@srvweb01> /usr/bin/nice -n 5 /usr/bin/php -q /var/www/froxlor/scripts/froxlor_master_cronjob.php --tasks 1> /dev/null
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
X-Cron-Env: <PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <LOGNAME=root>
Message-Id: <20221214201001.5901528560A@srvweb01.domain.tld>
Date: Wed, 14 Dec 2022 21:10:01 +0100 (CET)

froxlor[3246121]: The php PDO extension or PDO-MySQL driver is not available
froxlor[3246121]: --- DEBUG: #0 /var/www/froxlor/lib/Froxlor/Database/Database.php(219): Froxlor\Database\Database::getDB() #1 /var/www/froxlor/lib/Froxlor/Cron/MasterCron.php(221): Froxlor\Database\Database::__callStatic() #2 /var/www/froxlor/lib/Froxlor/Cron/MasterCron.php(41): Froxlor\Cron\MasterCron::init() #3 /var/www/froxlor/scripts/froxlor_master_cronjob.php(26): Froxlor\Cron\MasterCron::run() #4 {main}
```

**System information**
* Froxlor version: 0.10.38.3-1
* Web server: apache2
* DNS server: -
* POP/IMAP server: -
* SMTP server: -
* FTP server: -
* OS/Version: Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux

**Comment by d00p** [comment]
I guess you've updated/upgraded you system and your php-cli default version got updated and you are missing the required extensions for that other version of php. Try `update-alternatives` to set it back to the one you had before or install missing extensions

**Comment by mr-manuel** [comment]
Thanks for the very fast answer. Indeed I did also a system upgrade and missed that php-cli was updated to 8.2.

I solved it by installing php8.2-mysql with `apt install php8.2-mysql`.
