### ISSUE TITLE
Upgrade to 2.0.16 seems to break installation

### ISSUE THREAD

**Issue by herki84** [Froxlor/Froxlor#1134]
**Describe the bug**
After upgrading the debian package from 2.0.15 to 2.0.16 I am greeted with the following error instead of anything working:
```Uncaught exception
0 Typed property Froxlor\Http\RateLimiter::$limit_per_interval must be int, null used

#0 /var/www/html/froxlor/lib/init.php(125): Froxlor\Http\RateLimiter::run()
#1 /var/www/html/froxlor/index.php(27): require('/var/www/html/f...')
#2 {main}```

**System information**
* Froxlor version: 2.0.16
* Web server: apache2
* OS/Version: Debian 10

**To Reproduce**
Steps to reproduce the behavior:
Upgrade to 2.0.16, navigate to froxlor URL

**Expected behavior**
The usual upgrade process.

**Additional context**
I assume it tries to load the config value from the DB before it could do the DB migration and loads a "null" instead of a numeric value. Will try to add the config value manually and edit this post with the result.

**Comment by d00p** [comment]
Update to 2.0.17
