### ISSUE TITLE
Customer index: 405 You cannot access this resource

### ISSUE THREAD

**Issue by sorinpohontu** [Froxlor/Froxlor#1183]
I have updated one system to Froxlor 2.0.2.3 and from admin account I can't access customer area.

```
/customer_index.php
```
```
 Uncaught exception

405 You cannot access this resource

#0 /var/www/html/froxlor/lib/Froxlor/UI/Collection.php(132): Froxlor\Api\Commands\SubDomains->listingCount()
#1 /var/www/html/froxlor/lib/Froxlor/CurrentUser.php(156): Froxlor\UI\Collection->count()
#2 /var/www/html/froxlor/lib/navigation/00.froxlor.main.php(84): Froxlor\CurrentUser::canAddResource()
#3 /var/www/html/froxlor/lib/Froxlor/PhpHelper.php(235): include('...')
#4 /var/www/html/froxlor/lib/init.php(271): Froxlor\PhpHelper::loadConfigArrayDir()
#5 /var/www/html/froxlor/customer_index.php(27): require('...')
#6 {main}
```
**System information**
* Froxlor version: 2.0.2.3
* Web server: apache2
* DNS server:None
* POP/IMAP server: Dovecot
* SMTP server: postfix
* FTP server: proftpd/pureftpd
* OS/Version: Debian 12

Any hints ?

**Comment by d00p** [comment]
Does the target customer have domains disabled or no domains at all? Worked just fine for me, maybe I've missed something

**Comment by sorinpohontu** [comment]
Same error on any customer I click, also I can't login as customer. Last customer added has a domain, email only.

**Comment by sorinpohontu** [comment]
After errror, I have to clear cookies and site date from Firefox to log in again. I'm always redirected to `customer_index.php`.
Any log I can check ?

**Comment by sorinpohontu** [comment]
Yes

**Comment by d00p** [comment]
Okay, this option leads to the customer not being allowed to call "SubDomains.listingCount()" API methid, please try the following patch:

```diff
diff --git a/lib/Froxlor/CurrentUser.php b/lib/Froxlor/CurrentUser.php
index 26c836a3..211fd470 100644
--- a/lib/Froxlor/CurrentUser.php
+++ b/lib/Froxlor/CurrentUser.php
@@ -151,9 +151,13 @@ class CurrentUser
                        ]);
                        $addition = $result['emaildomains'] != 0;
                } elseif ($resource == 'subdomains') {
-                       $parentDomainCollection = (new Collection(SubDomains::class, $_SESSION['userinfo'],
-                               ['sql_search' => ['d.parentdomainid' => 0]]));
-                       $addition = $parentDomainCollection->count() != 0;
+                       if (Settings::IsInList('panel.customer_hide_options', 'domains')) {
+                               $addition = false;
+                       } else {
+                               $parentDomainCollection = (new Collection(SubDomains::class, $_SESSION['userinfo'],
+                                       ['sql_search' => ['d.parentdomainid' => 0]]));
+                               $addition = $parentDomainCollection->count() != 0;
+                       }
                } elseif ($resource == 'domains') {
                        $customerCollection = (new Collection(Customers::class, $_SESSION['userinfo']));
                        $addition = $customerCollection != 0;
```

**Comment by d00p** [comment]
Great, thanks for the feedback, very helpful :)
