### ISSUE TITLE
Certificate renewal error after 0.10.13 update

### ISSUE THREAD

**Issue by eleionomai** [Froxlor/Froxlor#804]
After update to version 0.10.13 all certificates aren't renewed on my installation.

```
/usr/bin/php5 -q /var/www/froxlor/scripts/froxlor_master_cronjob.php --tasks 1> /dev/null
--2020-02-10 19:40:01--  https://get.acme.sh/
Resolving get.acme.sh (get.acme.sh)... 104.31.88.68, 104.31.89.68, 2606:4700:3037::681f:5944, ...
Connecting to get.acme.sh (get.acme.sh)|104.31.88.68|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘STDOUT’

    0K                                                        22.3M=0s

2020-02-10 19:40:01 (22.3 MB/s) - written to stdout [775]

 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                Dload  Upload   Total   Spent    Left  Speed
 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  6  191k    6 12897    0     0   263k      0 --:--:-- --:--:-- --:--:-- 262k100  191k  100  191k    0     0  2662k      0 --:--:-- --:--:-- --:--:-- 2662k
[Mon Feb 10 19:40:03 CET 2020] It is recommended to install socat first.
[Mon Feb 10 19:40:03 CET 2020] We use socat for standalone server if you use standalone mode.
[Mon Feb 10 19:40:03 CET 2020] If you don't use standalone mode, just ignore this warning.
[Mon Feb 10 20:20:16 CET 2020] Sign failed, finalize code is not 200.
[Mon Feb 10 20:20:16 CET 2020] {
 "type": "urn:ietf:params:acme:error:orderNotReady",
 "detail": "Order's status (\"valid\") is not acceptable for finalization",
 "status": 403
}
[Mon Feb 10 20:20:16 CET 2020] Please add '--debug' or '--log' to check more details.
[Mon Feb 10 20:20:16 CET 2020] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Mon Feb 10 20:21:05 CET 2020] Sign failed, finalize code is not 200.
[Mon Feb 10 20:21:05 CET 2020] {
 "type": "urn:ietf:params:acme:error:orderNotReady",
 "detail": "Order's status (\"processing\") is not acceptable for finalization",
 "status": 403
}
[Mon Feb 10 20:21:05 CET 2020] Please add '--debug' or '--log' to check more details.
[Mon Feb 10 20:21:05 CET 2020] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Mon Feb 10 20:21:40 CET 2020] Sign failed, finalize code is not 200.
[Mon Feb 10 20:21:40 CET 2020] {
 "type": "urn:ietf:params:acme:error:orderNotReady",
 "detail": "Order's status (\"processing\") is not acceptable for finalization",
 "status": 403
}
[Mon Feb 10 20:21:40 CET 2020] Please add '--debug' or '--log' to check more details.
[Mon Feb 10 20:21:40 CET 2020] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Mon Feb 10 20:23:12 CET 2020] Sign failed, finalize code is not 200.
[Mon Feb 10 20:23:12 CET 2020] {
 "type": "urn:ietf:params:acme:error:orderNotReady",
 "detail": "Order's status (\"valid\") is not acceptable for finalization",
 "status": 403
}
[Mon Feb 10 20:23:12 CET 2020] Please add '--debug' or '--log' to check more details.
[Mon Feb 10 20:23:12 CET 2020] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Mon Feb 10 20:24:04 CET 2020] Sign failed, finalize code is not 200.
[Mon Feb 10 20:24:04 CET 2020] {
 "status": "valid",
 "expires": "2020-02-17T19:23:54Z",
 "identifiers": [
   {
     "type": "dns",
     "value": "XXXXX.de"
   },
   {
     "type": "dns",
     "value": "XXXXX.de"
   }
 ],
 "authorizations": [
   "https://acme-v02.api.letsencrypt.org/acme/authz-v3/12345",
   "https://acme-v02.api.letsencrypt.org/acme/authz-v3/12345"
 ],
 "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/12345/12345",
 "certificate": "https://acme-v02.api.letsencrypt.org/acme/cert/12345"
}
[Mon Feb 10 20:24:04 CET 2020] Please add '--debug' or '--log' to check more details.
[Mon Feb 10 20:24:04 CET 2020] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Mon Feb 10 20:24:21 CET 2020] Sign failed, finalize code is not 200.
[Mon Feb 10 20:24:21 CET 2020] {
 "type": "urn:ietf:params:acme:error:orderNotReady",
 "detail": "Order's status (\"valid\") is not acceptable for finalization",
 "status": 403
}
[Mon Feb 10 20:24:21 CET 2020] Please add '--debug' or '--log' to check more details.
[Mon Feb 10 20:24:21 CET 2020] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Mon Feb 10 20:24:49 CET 2020] Sign failed, finalize code is not 200.
[Mon Feb 10 20:24:49 CET 2020] {
 "type": "urn:ietf:params:acme:error:orderNotReady",
 "detail": "Order's status (\"valid\") is not acceptable for finalization",
 "status": 403
}
[Mon Feb 10 20:24:49 CET 2020] Please add '--debug' or '--log' to check more details.
[Mon Feb 10 20:24:49 CET 2020] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Mon Feb 10 20:25:53 CET 2020] Sign failed, finalize code is not 200.
[Mon Feb 10 20:25:53 CET 2020] {
 "type": "urn:ietf:params:acme:error:orderNotReady",
 "detail": "Order's status (\"valid\") is not acceptable for finalization",
 "status": 403
}
[Mon Feb 10 20:25:53 CET 2020] Please add '--debug' or '--log' to check more details.
[Mon Feb 10 20:25:53 CET 2020] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Mon Feb 10 20:26:24 CET 2020] Sign failed, finalize code is not 200.
[Mon Feb 10 20:26:24 CET 2020] {
 "type": "urn:ietf:params:acme:error:orderNotReady",
 "detail": "Order's status (\"valid\") is not acceptable for finalization",
 "status": 403
}
[Mon Feb 10 20:26:24 CET 2020] Please add '--debug' or '--log' to check more details.
[Mon Feb 10 20:26:24 CET 2020] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
froxlor[21531]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'ssl_ca_file' cannot be null
froxlor[21531]: --- DEBUG: #0 /var/www/froxlor/lib/Froxlor/Database/Database.php(83): PDOStatement->execute(Array) #1 /var/www/froxlor/lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php(369): Froxlor\Database\Database::pexecute(Object(PDOStatement), Array) #2 /var/www/froxlor/lib/Froxlor/Cron/Http/LetsEncrypt/AcmeSh.php(296): Froxlor\Cron\Http\LetsEncrypt\AcmeSh::runAcmeSh(Array, Array, 'issue', Object(Froxlor\FroxlorLogger), 1, false) #3 /var/www/froxlor/lib/Froxlor/Cron/Http/HttpConfigBase.php(37): Froxlor\Cron\Http\LetsEncrypt\AcmeSh::run(true) #4 /var/www/froxlor/lib/Froxlor/Cron/System/TasksCron.php(148): Froxlor\Cron\Http\HttpConfigBase->init() #5 /var/www/froxlor/lib/Froxlor/Cron/System/TasksCron.php(52): Froxlor\Cron\System\TasksCron::rebuildWebserverConfigs() #6 /var/www/froxlor/lib/Froxlor/Cron/MasterCron.php(111): Froxlor\Cron\System\TasksCron::run() #7 /var/www/froxlor/scripts/froxlor_master_cronjob.php(20): Froxlor\Cron\MasterCron::run() #8 {main}
```

# System information
* Froxlor version: 0.10.13 (DB: 201912313)
* OS/Version: Debian 3.16.74-1 (2019-09-24) x86_64 GNU/Linux

**Comment by d00p** [comment]
> /usr/bin/php5 -q /var/www/froxlor/scripts/froxlor_master_cronjob.php 

I'd say, first switch to php7.0+ which is required for froxlor, a miracle that the cronjob even runs.
Secondly, this looks more like a problem on acme.sh's side to me, see https://github.com/acmesh-official/acme.sh/issues/2544 and https://github.com/acmesh-official/acme.sh/issues/2557

Can you try running the cron manually with `--force --debug` parameters?

**Comment by hartl** [comment]
Froxlor PHP 7.2.27
Cron settings: `/usr/bin/nice -n 5 /usr/bin/php7.2 -q`

**Comment by d00p** [comment]
> Froxlor PHP 7.2.27
> Cron settings: `/usr/bin/nice -n 5 /usr/bin/php7.2 -q`

Well it's not what your log says ;)

**Comment by eleionomai** [comment]
Output with 7.2 cli (the panel is already running 7.2 fpm):
```
/usr/bin/php7.2 -q /var/www/froxlor/scripts/froxlor_master_cronjob.php --letsencrypt --debug --force                        
[information] Requesting/renewing Let's Encrypt certificates
[information] No new certificates or certificates due for renewal found
[information] TasksCron: Searching for tasks to do
[information] Running Let's Encrypt cronjob prior to regenerating webserver config files
[information] Requesting/renewing Let's Encrypt certificates
[information] No new certificates or certificates due for renewal found
...
```

**Comment by patschi** [comment]
I can see the same behavior on my Froxlor installation:
```
$ acme.sh --upgrade
[Sat Feb 15 18:05:39 UTC 2020] Installing from online archive.
[Sat Feb 15 18:05:39 UTC 2020] Downloading https://github.com/Neilpang/acme.sh/archive/master.tar.gz
[Sat Feb 15 18:05:41 UTC 2020] Extracting master.tar.gz
[Sat Feb 15 18:05:41 UTC 2020] Installing to /root/.acme.sh
[Sat Feb 15 18:05:41 UTC 2020] Installed to /root/.acme.sh/acme.sh
[Sat Feb 15 18:05:41 UTC 2020] Good, bash is found, so change the shebang to use bash as preferred.
[Sat Feb 15 18:05:41 UTC 2020] OK
[Sat Feb 15 18:05:41 UTC 2020] Install success!
[Sat Feb 15 18:05:42 UTC 2020] Upgrade success!

$ php /var/www/froxlor/scripts/froxlor_master_cronjob.php --letsencrypt --debug --force
PHP Notice:  Constant CRON_DEBUG_FLAG already defined in /var/www/froxlor/lib/Froxlor/Cron/MasterCron.php on line 76
PHP Notice:  Constant CRON_IS_FORCED already defined in /var/www/froxlor/lib/Froxlor/Cron/MasterCron.php on line 74
[information] TasksCron: Searching for tasks to do
[information] TasksCron: Task10 started - setting filesystem quota
[information] Task4 started - Rebuilding froxlor_bind.conf
[information] Cleaning dns zone files from /etc/bind/domains/
[information] No domains found for nameserver-config, skipping...
[information] Running Let's Encrypt cronjob prior to regenerating webserver config files
[information] Requesting/renewing Let's Encrypt certificates
[information] No new certificates or certificates due for renewal found
[...]
```

However there are enough certificates which should already be renewed:
![image](https://user-images.githubusercontent.com/2029878/74592928-0321a900-501e-11ea-889c-0303bfe4ac16.png)

**Comment by d00p** [comment]
Don't see why they should get renewed, they are valid more than 30 days...

**Comment by patschi** [comment]
> Don't see why they should get renewed, they are valid more than 30 days...

Okay, fair point. I thought LetsEncrypt recommends renewing every 30 days (maybe that recommendation changed at some point in the past?). However, I just read the [Let's Encrypt FAQ](https://letsencrypt.org/docs/faq/#what-is-the-lifetime-for-let-s-encrypt-certificates-for-how-long-are-they-valid):
```
We recommend automatically renewing your certificates every 60 days.
```

So... False alarm from my side. Sorry! Friend of mine had troubles with auto-renewal of his certificates in Froxlor. In my case the renewals should be done end of February then - I will keep an eye on it.

**Comment by d00p** [comment]
It used to be 30 days...and from what I understand, every 60 days would be 30 days before expiration as they are valid for 90 days ;)

**Comment by patschi** [comment]
Yes, I know. That's what I meant in my previous post: I still thought 30d were the recommended renewal interval, but I was wrong. :)
