### ISSUE TITLE
PHP Fatal Error with PHP 8.0

### ISSUE THREAD

**Issue by andlinger** [Froxlor/Froxlor#897]
We have just tested Froxlor on PHP8.0 
I know that it is not yet released, but probably it will be helpful for a future release.

If you switch to the "Configuration" menu item in the user interface the following error occurs:

```
mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Call to undefined function Froxlor\\Config\\simplexml_load_file() in /var/www/froxlor/lib/Froxlor/Config/ConfigParser.php:113, referer: https://host.example.com/froxlor/admin_cronjobs.php?page=overview&s=afc69447de2683eabba6faa45a16db51
mod_fcgid: stderr: Stack trace:, referer: https://host.example.com/froxlor/admin_cronjobs.php?page=overview&s=afc69447de2683eabba6faa45a16db51
mod_fcgid: stderr: #0 /var/www/froxlor/admin_configfiles.php(138): Froxlor\\Config\\ConfigParser->__construct('/var/www/froxlo...'), referer: https://host.example.com/froxlor/admin_cronjobs.php?page=overview&s=afc69447de2683eabba6faa45a16db51
mod_fcgid: stderr: #1 {main}, referer: https://host.example.com/froxlor/admin_cronjobs.php?page=overview&s=afc69447de2683eabba6faa45a16db51
mod_fcgid: stderr:   thrown in /var/www/froxlor/lib/Froxlor/Config/ConfigParser.php on line 113, referer: https://host.example.com/froxlor/admin_cronjobs.php?page=overview&s=afc69447de2683eabba6faa45a16db51
mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Call to undefined function Froxlor\\Config\\simplexml_load_file() in /var/www/froxlor/lib/Froxlor/Config/ConfigParser.php:113, referer: https://host.example.com/froxlor/admin_cronjobs.php?page=overview&s=afc69447de2683eabba6faa45a16db51
mod_fcgid: stderr: Stack trace:, referer: https://host.example.com/froxlor/admin_cronjobs.php?page=overview&s=afc69447de2683eabba6faa45a16db51
mod_fcgid: stderr: #0 /var/www/froxlor/admin_configfiles.php(138): Froxlor\\Config\\ConfigParser->__construct('/var/www/froxlo...'), referer: https://host.example.com/froxlor/admin_cronjobs.php?page=overview&s=afc69447de2683eabba6faa45a16db51
mod_fcgid: stderr: #1 {main}, referer: https://host.example.com/froxlor/admin_cronjobs.php?page=overview&s=afc69447de2683eabba6faa45a16db51
mod_fcgid: stderr:   thrown in /var/www/froxlor/lib/Froxlor/Config/ConfigParser.php on line 113, referer: https://host.example.com/froxlor/admin_cronjobs.php?page=overview&s=afc69447de2683eabba6faa45a16db51
```

**Comment by d00p** [comment]
`simplexml_load_file` is a php-builtin function....i hope php8 does not require to explicitly use the global namespace e.g. `\simplexml_load_file` or I will have a bit of work :)

**Comment by d00p** [comment]
Unable to reproduce on demo.froxlor.org

**Comment by d00p** [comment]
Most likely you are just missing php-xml
